package View;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
//import java.time.format.DateTimeFormatterBuilder;
//import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 * @author giovanna borges - cg3018334
 */

public class CadastroView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroView
     */
    
    MaskFormatter mfdata;
    
    public CadastroView() {
        try {
            //mfdata = new MaskFormatter("##/##/####");
            mfdata = new MaskFormatter("####-##-##");
        } catch (ParseException ex) {
            System.out.println("Erro: criação da máscara de data");
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_historimed = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        lbl_cpf = new javax.swing.JLabel();
        lbl_nascimento = new javax.swing.JLabel();
        lbl_sexo = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        cbox_sexo = new javax.swing.JComboBox<>();
        txt_email = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        box_termos = new javax.swing.JCheckBox();
        lbl_termos = new javax.swing.JLabel();
        txt_nascimento = new javax.swing.JFormattedTextField(mfdata);
        lbl_confirma = new javax.swing.JLabel();
        txt_confirma = new javax.swing.JPasswordField();
        btn_cadastrar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");

        lbl_historimed.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lbl_historimed.setText("HISTORIMED");

        lbl_nome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(0, 204, 153));
        lbl_nome.setText("Nome");

        lbl_cpf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_cpf.setForeground(new java.awt.Color(0, 204, 153));
        lbl_cpf.setText("CPF");

        lbl_nascimento.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_nascimento.setForeground(new java.awt.Color(0, 204, 153));
        lbl_nascimento.setText("Data de Nascimento");

        lbl_sexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_sexo.setForeground(new java.awt.Color(0, 204, 153));
        lbl_sexo.setText("Sexo");

        lbl_email.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 204, 153));
        lbl_email.setText("E-mail");

        lbl_senha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 204, 153));
        lbl_senha.setText("Senha");

        cbox_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Homem Cisgênero", "Homem Transgênero", "Mulher Cisgênero", "Mulher Transgênero" }));

        lbl_termos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_termos.setText("Li e Aceito os Termos e Condições");
        lbl_termos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_termosMouseClicked(evt);
            }
        });

        lbl_confirma.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_confirma.setForeground(new java.awt.Color(0, 204, 153));
        lbl_confirma.setText("Confirmar senha");

        btn_cadastrar.setBackground(new java.awt.Color(0, 204, 153));
        btn_cadastrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseClicked(evt);
            }
        });

        btn_voltar.setBackground(new java.awt.Color(0, 204, 153));
        btn_voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar.setText("Voltar");
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cpf)
                            .addComponent(lbl_nome))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_cpf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nascimento)
                            .addComponent(lbl_sexo)
                            .addComponent(lbl_email)
                            .addComponent(lbl_senha)
                            .addComponent(lbl_confirma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_confirma)
                            .addComponent(cbox_sexo, 0, 201, Short.MAX_VALUE)
                            .addComponent(txt_email)
                            .addComponent(txt_senha)
                            .addComponent(txt_nascimento))))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(box_termos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_termos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btn_voltar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lbl_historimed)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_historimed)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cpf)
                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nascimento)
                    .addComponent(txt_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_confirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_confirma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_termos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(box_termos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltar)
                    .addComponent(btn_cadastrar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_termosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_termosMouseClicked
        TermosView termosv = new TermosView();
        termosv.setVisible(true);
        
        CadastroView cadastrov = new CadastroView();
        cadastrov.setVisible(false);
    }//GEN-LAST:event_lbl_termosMouseClicked

    private void btn_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseClicked
        Cadastrar();
    }//GEN-LAST:event_btn_cadastrarMouseClicked

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        LoginView loginv = new LoginView();
        loginv.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box_termos;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> cbox_sexo;
    private javax.swing.JLabel lbl_confirma;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_historimed;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_termos;
    private javax.swing.JPasswordField txt_confirma;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JFormattedTextField txt_nascimento;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables

    private void AutenticacaoCpf() {
        try {
            long cpf;

            cpf = Long.parseLong(this.txt_cpf.getText());
            
            
            UsuarioDTO usuarioDto = new UsuarioDTO();
            usuarioDto.setCpf(cpf);

            UsuarioDAO usuarioDao = new UsuarioDAO();
            ResultSet rsusuarioDao = usuarioDao.autenticacaoCpf(usuarioDto);

            if (rsusuarioDao.next()) { // se tiver pelo menos 1 linha (1 usuário)
                // mandar mensagem de usuário já existe
                JOptionPane.showMessageDialog(null, "Parece que já nos conhecemos! Tente entrar com seu e-mail ou selecione 'Esqueceu a senha?'");
             
                LoginView loginv = new LoginView();
                loginv.setVisible(true);
                
                dispose();
            }

        } catch (SQLException erro) {
            System.out.println("Autenticação de CPF: " + erro);
        }
    }
    
    private void Cadastrar(){
        String nome, nascimentoS, sexo, email, senha, confirma;
        long cpf;
        
        // Verificar se o usuário já está cadastrado
        cpf = Long.parseLong(this.txt_cpf.getText());
        AutenticacaoCpf();
     
        nome = txt_nome.getText();
        nascimentoS = (String) txt_nascimento.getText();
        sexo = (String) cbox_sexo.getSelectedItem();
        email = txt_email.getText();
        senha = txt_senha.getText();
        confirma = txt_confirma.getText();
                
        // converter data de String para Date no formato do SQL
        /*DateTimeFormatter f = new DateTimeFormatterBuilder()
                                    .parseCaseInsensitive()
                                    .appendPattern("yyyy/MM/dd")
                                    .toFormatter(Locale.ENGLISH);
        LocalDate nascimentoLD = LocalDate.parse(nascimentoS, f);*/
        LocalDate nascimentoLD = LocalDate.parse(nascimentoS);
        
        if (senha.equals(confirma)){ // verificar se senha e confirmar senha são iguais
            if (box_termos.isSelected()){ // verificar se o usuário aceitou os termos e condições
                UsuarioDTO usuarioDto = new UsuarioDTO();
                usuarioDto.setNome(nome);
                usuarioDto.setCpf(cpf);
                usuarioDto.setNascimentoLD(nascimentoLD);
                usuarioDto.setNascimentoS(nascimentoS);
                usuarioDto.setSexo(sexo);
                usuarioDto.setEmail(email);
                usuarioDto.setSenha(senha);

                UsuarioDAO usuarioDao = new UsuarioDAO();
                usuarioDao.cadastrarUsuario(usuarioDto);
                
                PrincipalView principalv = new PrincipalView(usuarioDto);
                principalv.setVisible(true);

                dispose();
            } else
                JOptionPane.showMessageDialog(null, "O cadastro só pode ser realizado após o aceite dos Termos e Condições!");
        } else
            JOptionPane.showMessageDialog(null, "As senhas não coincidem. Tente novamente!");
    }
}