package View;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 * @author giovanna borges - cg3018334
 */

public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_historimed = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_senha = new javax.swing.JPasswordField();
        lbl_esqueciSenha = new javax.swing.JLabel();
        lbl_cadastrar = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));

        lbl_historimed.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lbl_historimed.setText("HISTORIMED");
        lbl_historimed.setToolTipText("");

        lbl_email.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 204, 153));
        lbl_email.setText("E-mail");

        lbl_senha.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 204, 153));
        lbl_senha.setText("Senha");

        lbl_esqueciSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_esqueciSenha.setText("Esqueceu a senha?");
        lbl_esqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_esqueciSenhaMouseClicked(evt);
            }
        });

        lbl_cadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cadastrar.setText("Cadastre-se");
        lbl_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cadastrarMouseClicked(evt);
            }
        });

        btn_entrar.setBackground(new java.awt.Color(0, 204, 153));
        btn_entrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entrar.setText("Entrar");
        btn_entrar.setName(""); // NOI18N
        btn_entrar.setOpaque(true);
        btn_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_entrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btn_entrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_cadastrar)
                                .addGap(19, 19, 19))
                            .addComponent(lbl_esqueciSenha, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_senha)
                            .addComponent(lbl_email))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_historimed)
                        .addGap(55, 55, 55)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(lbl_historimed)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addGap(18, 18, 18)
                .addComponent(btn_entrar)
                .addGap(18, 18, 18)
                .addComponent(lbl_esqueciSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_cadastrar)
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cadastrarMouseClicked
        CadastroView cadastrov = new CadastroView();
        cadastrov.setVisible(true);

        dispose();
    }//GEN-LAST:event_lbl_cadastrarMouseClicked

    private void lbl_esqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_esqueciSenhaMouseClicked
        EsqueciSenhaView esqueciv = new EsqueciSenhaView();
        esqueciv.setVisible(true);

        dispose();
    }//GEN-LAST:event_lbl_esqueciSenhaMouseClicked

    private void btn_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entrarMouseClicked
        try {
            Logar();
        } catch (SQLException erro) {
            System.out.println("Método Logar: " + erro);
        }
    }//GEN-LAST:event_btn_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JLabel lbl_cadastrar;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_esqueciSenha;
    private javax.swing.JLabel lbl_historimed;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables

    private void Logar() throws SQLException {
        String email, senha;
        
        email = txt_email.getText();
        senha = txt_senha.getText();
        
        UsuarioDTO usuarioDto = new UsuarioDTO();
        usuarioDto.setEmail(email);
        usuarioDto.setSenha(senha);
        
        UsuarioDAO usuarioDao = new UsuarioDAO();
        ResultSet rsusuarioDao = usuarioDao.autenticacaoUsuario(usuarioDto);
        
        if (rsusuarioDao.next()) { // se o resultado da consulta tiver pelo menos 1 linha
            // salvar todos os valores puxados da consulta na classe DTO
            //email e senha já foram passados
            usuarioDto.setNome(rsusuarioDao.getString("nome"));
            usuarioDto.setCpf(rsusuarioDao.getLong("cpf"));
            usuarioDto.setSexo(rsusuarioDao.getString("sexo"));
            usuarioDto.setNascimentoS(rsusuarioDao.getString("nascimento"));
            
            // chamar a tela principal
            PrincipalView principalv = new PrincipalView(usuarioDto);
            principalv.setVisible(true);

            dispose(); // fecha a tela atual
        } else {
            // enviar mensagem de usuário ou senha incorreta
            JOptionPane.showMessageDialog(null, "Usuário ou Senha Inválida! Tente novamente.");
        }
    }
}
