package View;

import DAO.UsuarioDAO;
import DTO.UsuarioDTO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 * @author giovanna borges - cg3018334
 */

public class PerfilView extends javax.swing.JFrame {

    /**
     * Creates new form PerfilView
     */
    //MaskFormatter mfdata;
    UsuarioDTO usuarioDto;

    public PerfilView(UsuarioDTO usuarioDto) {
        /*try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Erro: criação da máscara de data");
        }*/

        initComponents();

        this.usuarioDto = usuarioDto;
        
        txt_nome.setText(usuarioDto.getNome());
        txt_cpf.setText(Long.toString(usuarioDto.getCpf()));
        txt_nascimento.setText(usuarioDto.getNascimentoS());
        cbox_sexo.setSelectedItem(usuarioDto.getSexo());
        txt_email.setText(usuarioDto.getEmail());
        txt_senha.setText(usuarioDto.getSenha());
    }

    public PerfilView() {
        initComponents();
        System.out.println("Página Perfil: ERRO! NÃO USAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new javax.swing.JTextField();
        cbox_sexo = new javax.swing.JComboBox<>();
        txt_email = new javax.swing.JTextField();
        lbl_historimed = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        lbl_nome = new javax.swing.JLabel();
        lbl_nascimento = new javax.swing.JLabel();
        lbl_sexo = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        txt_cpf = new javax.swing.JTextField();
        btn_excluir = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        txt_nascimento = new javax.swing.JTextField();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil");

        cbox_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Homem Cisgênero", "Homem Transgênero", "Mulher Cisgênero", "Mulher Transgênero" }));

        lbl_historimed.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lbl_historimed.setText("HISTORIMED");

        lbl_nome.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_nome.setForeground(new java.awt.Color(0, 204, 153));
        lbl_nome.setText("Nome");

        lbl_nascimento.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_nascimento.setForeground(new java.awt.Color(0, 204, 153));
        lbl_nascimento.setText("Data de Nascimento");

        lbl_sexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_sexo.setForeground(new java.awt.Color(0, 204, 153));
        lbl_sexo.setText("Sexo");

        lbl_email.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 204, 153));
        lbl_email.setText("E-mail");

        lbl_senha.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 204, 153));
        lbl_senha.setText("Senha");

        btn_salvar.setBackground(new java.awt.Color(0, 204, 153));
        btn_salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_salvar.setForeground(new java.awt.Color(255, 255, 255));
        btn_salvar.setText("Salvar");
        btn_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salvarMouseClicked(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(0, 204, 153));
        btn_excluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_excluir.setText("Excluir Conta");
        btn_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_excluirMouseClicked(evt);
            }
        });

        btn_voltar.setBackground(new java.awt.Color(0, 204, 153));
        btn_voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_voltar.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar.setText("Voltar");
        btn_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voltarMouseClicked(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(0, 204, 153));
        btn_sair.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setText("Sair");
        btn_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_excluir)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sair))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btn_voltar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_salvar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nome)
                            .addComponent(lbl_nascimento)
                            .addComponent(lbl_sexo)
                            .addComponent(lbl_email)
                            .addComponent(lbl_senha))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbox_sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_email)
                                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lbl_historimed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_historimed)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nome)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nascimento)
                    .addComponent(txt_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sexo)
                    .addComponent(cbox_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_senha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_voltar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_excluir)
                    .addComponent(btn_sair))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvarMouseClicked
        AtualizarPerfil();
    }//GEN-LAST:event_btn_salvarMouseClicked

    private void btn_excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_excluirMouseClicked
        ConfirmaExcluirView excluirv = new ConfirmaExcluirView(usuarioDto);
        excluirv.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btn_excluirMouseClicked

    private void btn_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voltarMouseClicked
        PrincipalView principalv = new PrincipalView(usuarioDto);
        principalv.setVisible(true);

        dispose();
    }//GEN-LAST:event_btn_voltarMouseClicked

    private void btn_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sairMouseClicked
        LoginView loginv = new LoginView();
        loginv.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_btn_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<String> cbox_sexo;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_historimed;
    private javax.swing.JLabel lbl_nascimento;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nascimento;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    // End of variables declaration//GEN-END:variables

    private void AtualizarPerfil() {
        String nome, nascimentoS, sexo, email, senha;

        nome = txt_nome.getText();
        nascimentoS = (String) txt_nascimento.getText();
        sexo = (String) cbox_sexo.getSelectedItem();
        email = txt_email.getText();
        senha = txt_senha.getText();
        
        LocalDate nascimentoLD = LocalDate.parse(nascimentoS); // converter String para LocalDate

        UsuarioDTO usuarioDto = new UsuarioDTO();
        usuarioDto.setNome(nome);
        usuarioDto.setNascimentoLD(nascimentoLD);
        usuarioDto.setNascimentoS(nascimentoS);
        usuarioDto.setSexo(sexo);
        usuarioDto.setEmail(email);
        usuarioDto.setSenha(senha);

        UsuarioDAO usuarioDao = new UsuarioDAO();
        usuarioDao.alterarPerfil(usuarioDto);
        
        JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
        
        PrincipalView principalv = new PrincipalView(usuarioDto);
        principalv.setVisible(true);
        
        dispose();
    }
}
