package View;

import DTO.UsuarioDTO;
import javax.swing.JOptionPane;

/**
 * @author giovanna borges - cg3018334
 */

public class PrincipalView extends javax.swing.JFrame {

    private UsuarioDTO usuarioDto;

    public PrincipalView(UsuarioDTO usuarioDto) {
        initComponents();
        
        this.usuarioDto = usuarioDto;
        lbl_ola.setText("Olá, " + usuarioDto.getNome());
    }

    public PrincipalView() {
        initComponents();
        System.out.println("Página Principal: ERRO! NÃO USE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lbl_home_historimed = new javax.swing.JLabel();
        lbl_ola = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        btn_historico = new javax.swing.JButton();
        btn_compartilhar = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_home_perfil = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_home_historimed.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lbl_home_historimed.setText("HISTORIMED");

        lbl_ola.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbl_ola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ola.setText("Olá, usuário");
        lbl_ola.setToolTipText("");
        lbl_ola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_olaMouseClicked(evt);
            }
        });

        btn_enviar.setBackground(new java.awt.Color(0, 204, 153));
        btn_enviar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_enviar.setForeground(new java.awt.Color(255, 255, 255));
        btn_enviar.setText("Enviar Exames");
        btn_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_enviarMouseClicked(evt);
            }
        });

        btn_historico.setBackground(new java.awt.Color(0, 204, 153));
        btn_historico.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_historico.setForeground(new java.awt.Color(255, 255, 255));
        btn_historico.setText("Acessar Histórico");
        btn_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_historicoMouseClicked(evt);
            }
        });

        btn_compartilhar.setBackground(new java.awt.Color(0, 204, 153));
        btn_compartilhar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_compartilhar.setForeground(new java.awt.Color(255, 255, 255));
        btn_compartilhar.setText("Compartilhar");
        btn_compartilhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_compartilharMouseClicked(evt);
            }
        });

        menu_home_perfil.setBackground(new java.awt.Color(0, 204, 153));
        menu_home_perfil.setText("Perfil");
        menu_home_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_home_perfilMouseClicked(evt);
            }
        });
        jMenuBar2.add(menu_home_perfil);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_home_historimed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_historico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_compartilhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_home_historimed)
                .addGap(28, 28, 28)
                .addComponent(lbl_ola)
                .addGap(18, 18, 18)
                .addComponent(btn_enviar)
                .addGap(18, 18, 18)
                .addComponent(btn_historico)
                .addGap(18, 18, 18)
                .addComponent(btn_compartilhar)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_olaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_olaMouseClicked
        PerfilView perfilv = new PerfilView(usuarioDto);
        perfilv.setVisible(true);

        dispose();
    }//GEN-LAST:event_lbl_olaMouseClicked

    private void menu_home_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_home_perfilMouseClicked
        PerfilView perfilv = new PerfilView(usuarioDto);
        perfilv.setVisible(true);

        dispose();
    }//GEN-LAST:event_menu_home_perfilMouseClicked

    private void btn_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_enviarMouseClicked
        JOptionPane.showMessageDialog(null, "Ops, essa página ainda está em construção!");
    }//GEN-LAST:event_btn_enviarMouseClicked

    private void btn_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historicoMouseClicked
        JOptionPane.showMessageDialog(null, "Ops, essa página ainda está em construção!");
    }//GEN-LAST:event_btn_historicoMouseClicked

    private void btn_compartilharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_compartilharMouseClicked
        JOptionPane.showMessageDialog(null, "Ops, essa página ainda está em construção!");
    }//GEN-LAST:event_btn_compartilharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_compartilhar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_historico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl_home_historimed;
    private javax.swing.JLabel lbl_ola;
    private javax.swing.JMenu menu_home_perfil;
    // End of variables declaration//GEN-END:variables
}
